fm_elfinder:
    assets_path: /assets
    instances:
        default:
            connector:
                roots:
                    uploads:
                        driver: LocalFileSystem
                        path: uploads


